### PR TITLE
Add prompt option

### PR DESCRIPTION
**Pull request by yasirtrimulabs**

### CODE REVIEW

**Comment by soofstad** [comment]
Hi, thank you for your pull request :) 

Do you mind explaining a bit about why this change is needed, and what it does?

It would be nice to see some comments alongside the config parameters in-code.

**Comment by soofstad** [comment]
I assume this is for use-cases like this; https://developers.google.com/identity/protocols/oauth2/web-server#creatingclient, where Google allows for the non-standard 'prompt' parameter in the authorization request.

I'm reluctant to add non-RFC specified configuration parameters to the configuration, but seeing how usual it is for auth providers to add custom parameters, I think a good feature would be to add a `extraAuthParameters?: {[key: string]: string|boolean|number}` to the TAuthConfig type. Each key-value pair from this object should then get added to the auth request.

**Comment by yasirtrimulabs** [comment]
@soofstad hi,
Sorry I will close this one I created another package from a fork for my use case I was integrating my project with a third party and wanted to make it so that the user have to login everytime that's why I needed prompt option.
Thanks again for the repo btw.

**Comment by yasirtrimulabs** [comment]
Package link if someone needs it 
https://www.npmjs.com/package/react-pkce-oauth2

**Comment by soofstad** [comment]
If you have a need for this feature, I'm sure others will as well. The goal of the library is to be compatible with as many different auth providers as possible, while still beeing easy to use and configure.

So I do want to support this, but in a bit different way than the one you proposed.

**Comment by yasirtrimulabs** [comment]
> If you have a need for this feature, I'm sure others will as well. The goal of the library is to be compatible with as many different auth providers as possible, while still beeing easy to use and configure.
> 
> So I do want to support this, but in a bit different way than the one you proposed.

Looking forward to that. Thanks

**Comment by soofstad** [comment]
Just want to let you know. This is now supported through the "extraAuthParams" configuration parameter.
Available from version `1.5.0`

**Comment by yasirtrimulabs** [comment]
Thank you very much

**Pull request closed without merging**
